[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
nixPkgs = ["...", "ffmpeg"]
[phases.build]
cmds = ["cd backend && npm install && npx prisma generate"]

[start]
cmd = "cd backend && npx prisma migrate deploy && node src/index.js"